title = "Main user config file"
comment = "Feel free to modify for your requirements."

[Release]
ORIGINAL_IMAGE = "2019-09-26-raspbian-buster-lite.img"
REMASTERED_IMAGE = "2019-09-26-raspbian-buster-lite-remastered.img"
INCREASE_DISK_SIZE_AMOUNT_MB = 2048
ARCH = "arm"

[Config]
KEYBOARD = "us"
LOCALE = "en_AU.UTF-8"
TIMEZONE = "Australia/Melbourne"


