title = "Main user config file"
comment = "Feel free to modify for your requirements."

[Release]
ORIGINAL_IMAGE = "2019-09-26-raspbian-buster-lite.img"
REMASTERED_IMAGE = "2019-09-26-raspbian-buster-lite-remastered.img"
INCREASE_DISK_SIZE_AMOUNT_MB = 2048
ARCH = "arm"

[Raspbian]
KEYBOARD = "us"
LOCALE = "en_AU.UTF-8"
TIMEZONE = "Australia/Melbourne"

[Raspbian.Interfaces]
I2C=true
SPI=false
SERIAL=false
VNC=false
CAMERA=false

[Raspbian.Wifis]
COUNTRY= "AU"

[[Raspbian.Wifi.Wifi]]
SSID = "MelbPC-NUE"
PSK = "peachspeak38"
KEYMGMT = "WPA-PSK" 

[[Raspbian.Wifi.Wifi]]
SSID = "mycrib" 
PSK = "peachspeak38"
KEYMGMT = "WPA-PSK"

