title = "Main user config file"
comment = "Feel free to modify for your requirements."

[Release]
#ORIGINAL_IMAGE = "2019-09-26-raspbian-buster.img"
#REMASTERED_IMAGE = "2019-09-26-raspbian-buster-remastered.img"
ORIGINAL_IMAGE = "ubuntu-19.10-preinstalled-server-arm64+raspi3.img"
REMASTERED_IMAGE = "ubuntu-19.10-preinstalled-server-arm64+raspi3-remastered.img"
INCREASE_DISK_SIZE_AMOUNT_MB = 3064
ARCH = "aarch64"
#ARCH = "arm"

[Locale]
LC_ALL = "en_AU.UTF-8"

[Keyboard]
XKBLAYOUT="us"

[TimeZone]
TIMEZONE = "Australia/Melbourne"

[Wifi]
  [Wifi.Home]
  COUNTRY = "AU"
  SSID = "mycrib"
  PSK = "peachspeak38"
  KEYMGMT = "WPA-PSK"
  [Wifi.Away]
  COUNTRY = "AU"
  SSID = "MelbPC-NUE"
  PSK = "peachspeak38"
  KEYMGMT = "WPA-PSK"


